name: my_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=23.2.1
  - pip:
    - jupyter==1.0.0
    - pandas==1.0.0
    - scikit-learn==1.3.0
    - pandas==2.1.0
    - numpy==1.25.2
    - matplotlib==3.7.2
    - seaborn==0.10.0
    - black==19.10b0
    - haversine==2.2.0
    - toml==0.10.0
    - mlflow==2.6.0
    - notebook==7.0.3
    - dvc-s3==2.23.0
    - python-box==7.1.1
    - pyYAML==6.0.1
    - tqdm==4.66.1
    - ensure==1.0.3
    - joblib==1.3.2
    - types-PyYAML==6.0.12.11
    - Flask==2.3.3
    - dvc==3.19.0
    - xgboost==2.0.0
    - catboost==1.2.1.1
    - seaborn==0.12.2
    - Flask-Cors==4.0.0
    - -e .
